# Generated by Django 5.2 on 2025-05-12 03:48

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='unique_identifier',
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='认证通过的时间', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='审核此用户的管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_teachers', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='certificate',
            field=models.FileField(blank=True, help_text='上传的教师资格证或学历证明', null=True, upload_to='certificates/', validators=[users.models.validate_certificate_file]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(choices=[('primary', 'PRIMARY'), ('middle', 'MIDDLE'), ('high', 'HIGH'), ('bachelor', 'BACHELOR'), ('master', 'MASTER'), ('phd', 'PHD')], default='primary', help_text='用户的学历等级', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified_teacher',
            field=models.BooleanField(default=False, help_text='是否通过认证'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER'), ('admin', 'ADMIN')], default='student', max_length=10),
        ),
    ]
