# Generated by Django 5.2 on 2025-05-14 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='following_teachers',
            field=models.ManyToManyField(blank=True, help_text='当前用户关注的教师', limit_choices_to={'is_verified_teacher': True}, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
