# Generated by Django 5.2 on 2025-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_role_customuser_following_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', help_text='user, admin', max_length=20),
        ),
    ]
