# Generated by Django 5.2 on 2025-05-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='review_comment',
            field=models.TextField(blank=True, help_text='认证审核意见（仅审核不通过时填写）', null=True),
        ),
    ]
