# Generated by Django 5.2 on 2025-04-24 01:39

import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='videos/', validators=[videos.models.validate_video_file, videos.models.validate_video_duration])),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_access', to='users.customuser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='videos.video')),
            ],
        ),
    ]
