# Generated by Django 5.2 on 2025-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_free_watch_duration_alter_video_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'PRIMARY'), ('middle', 'MIDDLE'), ('high', 'HIGH'), ('bachelor', 'BACHELOR'), ('master', 'MASTER'), ('phd', 'PHD')], default='', help_text='视频适合的学历等级', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='视频所属学科', max_length=20, null=True),
        ),
    ]
