# Generated by Django 5.2 on 2025-05-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_education_level_video_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
