# Generated by Django 5.2 on 2025-05-20 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        ('videos', '0003_video_education_level_video_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='videos.video'),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(default=5),
        ),
    ]
