# Generated by Django 5.2 on 2025-05-20 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_scorecorrectionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField()),
                ('teacher_score', models.FloatField()),
                ('ai_comment', models.TextField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_logs', to='homework.studentanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.question')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
