# Generated by Django 5.2 on 2025-05-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_subjectivecorrectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomeworkresult',
            name='status',
            field=models.CharField(default='graded', max_length=16),
        ),
    ]
