# Generated by Django 5.2 on 2025-05-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_alter_studenthomeworkresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomeworkresult',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
